package:
  name: wand-server
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  path: ../..

build:
  noarch: python
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py38_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_DESCRIBE_HASH", "")[1:] }}
  entry_points:
      - wand_gui = wand.frontend.wand_gui:main
      - wand_locker = wand.frontend.wand_locker:main
      - wand_influx_db = wand.frontend.wand_influx_db:main
      - wand_server = wand.frontend.wand_server:main
  script: python setup.py install

requirements:
  build:
    - python >=3.8
  run:
    - python >=3.8
    - artiq
    - numpy
    - scipy
    - PyDAQmx
